version: '3'
services:
  movie:
    image: penchaldock/phonepaymovies:v1
    ports: 
      - "8000:80"
    deploy:
      replicas: 4

  train:
    image: penchaldock/phonepaytrains:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 4

  loan:
    image: penchaldock/phonepayloans:v1
    ports:
      - "8002:80"
    deploy:
      replicas: 4
